/**
 * =============================================
 *  T&M Online Fashions — Product Catalog
 * =============================================
 *  Central product data for all pages.
 *  When Shopify is connected, this acts as fallback/seed data.
 */

(function () {
    'use strict';

    const ProductsCatalog = [

        // ── SAREES ─────────────────────────────────────
        {
            id: 'SR1001',
            name: 'Red Crepe Ready To Wear Saree with Silk Blouse and Embroidery',
            sku: 'SR1001',
            category: 'Women',
            subcategory: 'Sarees',
            price: 15990,
            compareAtPrice: 19990,
            currency: '₹',
            deliveryDays: '3 to 5 Working Days',
            availability: 'In Stock',
            emiPerMonth: 563,
            images: [
                './images/image-1.webp',
                './images/image-2.webp',
                './images/image-3.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'Free Size', value: 'FREE' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Saree Measurements',
            details: {
                fabric: 'Crepe with Silk Blouse',
                work: 'Thread Embroidery, Sequins',
                blouse: 'Stitched Silk Blouse',
                dupatta: 'N/A',
                lining: 'Satin Inner',
                weight: '1.2 kg (approx)',
                occasion: 'Party, Wedding, Festive',
                washCare: 'Dry Clean Only',
                deliveryTime: '3–5 Working Days (Ready to Ship)',
            },
            description: `<p>Make a statement in this gorgeous <strong>Red Crepe Ready To Wear Saree</strong> paired with a stunning silk blouse. The saree features intricate thread embroidery and sequin detailing.</p>
<ul><li>Pre-stitched for effortless draping</li><li>Silk blouse with embroidery included</li><li>Perfect for parties and festive occasions</li></ul>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 3–5 Working Days</li><li>International: 7–12 Working Days</li><li>Tracking provided via email & SMS</li></ul><p><strong>Returns:</strong> 7-day return policy. Items must be unused.</p>`,
        },
        {
            id: 'SR1002',
            name: 'Black Lycra Ready To Wear Saree with Embroidered Sleeveless Blouse',
            sku: 'SR1002',
            category: 'Women',
            subcategory: 'Sarees',
            price: 18490,
            compareAtPrice: 22990,
            currency: '₹',
            deliveryDays: '3 to 5 Working Days',
            availability: 'In Stock',
            emiPerMonth: 651,
            images: [
                './images/image-2.webp',
                './images/image-1.webp',
                './images/image-3.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'Free Size', value: 'FREE' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Saree Measurements',
            details: {
                fabric: 'Premium Lycra',
                work: 'Heavy Embroidery, Stone Work',
                blouse: 'Sleeveless Embroidered Blouse',
                dupatta: 'N/A',
                lining: 'Satin Inner',
                weight: '1.0 kg (approx)',
                occasion: 'Cocktail, Reception, Party',
                washCare: 'Dry Clean Only',
                deliveryTime: '3–5 Working Days (Ready to Ship)',
            },
            description: `<p>A contemporary <strong>Black Lycra Ready To Wear Saree</strong> designed for the modern woman. Features a stunning embroidered sleeveless blouse.</p>
<ul><li>Lycra fabric for a body-hugging fit</li><li>Pre-draped for easy wearing</li><li>Embroidered blouse included</li></ul>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 3–5 Working Days</li><li>International: 7–12 Working Days</li></ul><p><strong>Returns:</strong> 7-day return policy.</p>`,
        },
        {
            id: 'SR1003',
            name: 'Kanchipuram Pure Silk Saree with Zari Border and Pallu',
            sku: 'SR1003',
            category: 'Women',
            subcategory: 'Sarees',
            price: 35000,
            compareAtPrice: 42000,
            currency: '₹',
            deliveryDays: '5 to 7 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1232,
            images: [
                './images/image-7.webp',
                './images/image-1.webp',
                './images/image-2.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'Free Size', value: 'FREE' },
            ],
            measurementLink: 'Saree Measurements',
            details: {
                fabric: 'Pure Kanchipuram Silk',
                work: 'Traditional Zari Weaving',
                blouse: 'Running Blouse Piece (Unstitched)',
                dupatta: 'N/A',
                lining: 'N/A',
                weight: '0.9 kg (approx)',
                occasion: 'Wedding, Bridal, Puja',
                washCare: 'Dry Clean Only',
                deliveryTime: '5–7 Working Days',
            },
            description: `<p>A timeless <strong>Kanchipuram Pure Silk Saree</strong> featuring intricate zari border and pallu work woven by master artisans from Tamil Nadu.</p>
<ul><li>100% pure mulberry silk</li><li>Handwoven zari border</li><li>Running blouse piece included</li></ul>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 5–7 Working Days</li><li>International: 10–15 Working Days</li></ul>`,
        },
        {
            id: 'SR1004',
            name: 'Banarasi Silk Saree with Heavy Zari Work and Tassels',
            sku: 'SR1004',
            category: 'Women',
            subcategory: 'Sarees',
            price: 28500,
            compareAtPrice: 34000,
            currency: '₹',
            deliveryDays: '5 to 7 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1003,
            images: [
                './images/image-5.webp',
                './images/image-6.webp',
                './images/image-7.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'Free Size', value: 'FREE' },
            ],
            measurementLink: 'Saree Measurements',
            details: {
                fabric: 'Banarasi Silk',
                work: 'Heavy Zari, Tassels',
                blouse: 'Running Blouse Piece',
                dupatta: 'N/A',
                lining: 'N/A',
                weight: '1.1 kg (approx)',
                occasion: 'Wedding, Festive, Bridal',
                washCare: 'Dry Clean Only',
                deliveryTime: '5–7 Working Days',
            },
            description: `<p>Drape yourself in royalty with this <strong>Banarasi Silk Saree</strong> featuring heavy zari work and ornamental tassels. Handcrafted in Varanasi.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 5–7 Days</li><li>International: 10–15 Days</li></ul>`,
        },

        // ── LEHENGAS ───────────────────────────────────
        {
            id: 'LH2001',
            name: 'Crimson Red Umbrella Style Silk Bridal Lehenga with Elbow Sleeve Blouse',
            sku: 'LH2001',
            category: 'Women',
            subcategory: 'Lehenga',
            price: 51500,
            compareAtPrice: 62000,
            currency: '₹',
            deliveryDays: '40 to 45 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1811,
            images: [
                './images/image-1.webp',
                './images/image-2.webp',
                './images/image-3.webp',
                './images/image-4.webp',
                './images/image-5.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'XS (34)', value: 'XS' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'XXL (44)', value: 'XXL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Lehenga Measurements',
            details: {
                fabric: 'Pure Silk with Zari Work',
                work: 'Zari, Sequins, Stone, Resham Embroidery',
                blouse: 'Elbow Sleeve Blouse (Stitched)',
                dupatta: 'Heavy Embroidered Net Dupatta',
                lining: 'Cancan + Cotton Inner',
                weight: '4.5 kg (approx)',
                occasion: 'Wedding, Bridal, Reception',
                washCare: 'Dry Clean Only',
                deliveryTime: '40–45 Working Days (Custom Made)',
            },
            description: `<p>Be the most stunning bride in this magnificent <strong>Crimson Red Umbrella Style Silk Bridal Lehenga</strong>. Crafted from the finest pure silk, this lehenga features an umbrella cut silhouette.</p>
<ul><li>Pure silk fabric with rich zari weaving</li><li>Umbrella cut for a royal silhouette</li><li>Elbow sleeve stitched blouse included</li><li>Heavy embroidered net dupatta included</li></ul>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 40–45 Working Days (Made to Order)</li><li>International: 45–55 Working Days</li><li>Tracking provided via email & SMS</li></ul><p><strong>Returns:</strong> Exchange only for custom-made products.</p>`,
        },
        {
            id: 'LH2002',
            name: 'Gold Sequins Embroidered Shimmer Designer Lehenga with Sweetheart Neck',
            sku: 'LH2002',
            category: 'Women',
            subcategory: 'Lehenga',
            price: 25000,
            compareAtPrice: 30000,
            currency: '₹',
            deliveryDays: '35 to 40 Working Days',
            availability: 'In Stock',
            emiPerMonth: 880,
            images: [
                './images/image-3.webp',
                './images/image-4.webp',
                './images/image-5.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Lehenga Measurements',
            details: {
                fabric: 'Shimmer Georgette',
                work: 'Sequins, Thread Embroidery',
                blouse: 'Sweetheart Neck Blouse (Stitched)',
                dupatta: 'Net Dupatta with Sequin Border',
                lining: 'Satin Inner',
                weight: '3.2 kg (approx)',
                occasion: 'Reception, Cocktail, Sangeet',
                washCare: 'Dry Clean Only',
                deliveryTime: '35–40 Working Days',
            },
            description: `<p>Dazzle at any celebration in this <strong>Gold Sequins Embroidered Shimmer Lehenga</strong>. The sweetheart neckline blouse adds a contemporary edge.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 35–40 Working Days</li><li>International: 40–50 Working Days</li></ul>`,
        },
        {
            id: 'LH2003',
            name: 'Beige Sequins Embroidered Net Promotional Lehenga with Resham and Stone',
            sku: 'LH2003',
            category: 'Women',
            subcategory: 'Lehenga',
            price: 32500,
            compareAtPrice: 39000,
            currency: '₹',
            deliveryDays: '35 to 40 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1144,
            images: [
                './images/image-4.webp',
                './images/image-3.webp',
                './images/image-5.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Lehenga Measurements',
            details: {
                fabric: 'Premium Net with Satin Lining',
                work: 'Sequins, Resham, Stone Work',
                blouse: 'V-Neck Blouse (Stitched)',
                dupatta: 'Embroidered Net Dupatta',
                lining: 'Satin + Cancan',
                weight: '3.5 kg (approx)',
                occasion: 'Wedding, Engagement, Reception',
                washCare: 'Dry Clean Only',
                deliveryTime: '35–40 Working Days',
            },
            description: `<p>Exude grace in this <strong>Beige Sequins Embroidered Net Lehenga</strong> featuring intricate resham and stone work.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 35–40 Working Days</li><li>International: 40–50 Working Days</li></ul>`,
        },
        {
            id: 'LH2004',
            name: 'Orange Sequins Embroidered Net Lehenga with Resham and Stone Work',
            sku: 'LH2004',
            category: 'Women',
            subcategory: 'Lehenga',
            price: 29900,
            compareAtPrice: 36000,
            currency: '₹',
            deliveryDays: '35 to 40 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1053,
            images: [
                './images/image-5.webp',
                './images/image-4.webp',
                './images/image-3.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Lehenga Measurements',
            details: {
                fabric: 'Premium Net',
                work: 'Sequins, Resham, Stone',
                blouse: 'Round Neck Blouse (Stitched)',
                dupatta: 'Net Dupatta',
                lining: 'Satin Inner',
                weight: '3.3 kg (approx)',
                occasion: 'Haldi, Mehendi, Sangeet',
                washCare: 'Dry Clean Only',
                deliveryTime: '35–40 Working Days',
            },
            description: `<p>Shine bright in this vibrant <strong>Orange Sequins Embroidered Net Lehenga</strong> with beautiful resham and stone work.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 35–40 Working Days</li><li>International: 40–50 Working Days</li></ul>`,
        },
        {
            id: 'LH2005',
            name: 'Blush Pink Sequins Embroidered Georgette Lehenga with Ruffle Dupatta',
            sku: 'LH2005',
            category: 'Women',
            subcategory: 'Lehenga',
            price: 42000,
            compareAtPrice: 50000,
            currency: '₹',
            deliveryDays: '40 to 45 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1478,
            images: [
                './images/image-6.webp',
                './images/image-5.webp',
                './images/image-4.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'XS (34)', value: 'XS' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Lehenga Measurements',
            details: {
                fabric: 'Georgette with Sequins',
                work: 'Heavy Sequin Embroidery',
                blouse: 'Off-Shoulder Blouse (Stitched)',
                dupatta: 'Ruffle Net Dupatta',
                lining: 'Cancan + Satin',
                weight: '3.8 kg (approx)',
                occasion: 'Wedding, Bridal, Reception',
                washCare: 'Dry Clean Only',
                deliveryTime: '40–45 Working Days',
            },
            description: `<p>The epitome of bridal elegance — this <strong>Blush Pink Georgette Lehenga</strong> features lavish sequin embroidery with a stunning ruffle dupatta.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 40–45 Working Days</li><li>International: 45–55 Working Days</li></ul>`,
        },

        // ── SUITS / ANARKALI ───────────────────────────
        {
            id: 'AN3001',
            name: 'Emerald Green Zari Embroidered Silk Anarkali Suit with Network Dupatta',
            sku: 'AN3001',
            category: 'Women',
            subcategory: 'Salwar Kameez',
            price: 21500,
            compareAtPrice: 26000,
            currency: '₹',
            deliveryDays: '30 to 35 Working Days',
            availability: 'In Stock',
            emiPerMonth: 757,
            images: [
                './images/image-7.webp',
                './images/image-6.webp',
                './images/image-5.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Anarkali Measurements',
            details: {
                fabric: 'Pure Silk',
                work: 'Zari Embroidery',
                blouse: 'N/A (Full-length Kurta)',
                dupatta: 'Net Dupatta with Zari Border',
                lining: 'Cotton Inner',
                weight: '2.5 kg (approx)',
                occasion: 'Wedding, Festive, Engagement',
                washCare: 'Dry Clean Only',
                deliveryTime: '30–35 Working Days',
            },
            description: `<p>Command elegance with this <strong>Emerald Green Zari Embroidered Silk Anarkali</strong>. The floor-length silhouette pairs with a luxurious network dupatta.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 30–35 Working Days</li><li>International: 35–45 Working Days</li></ul>`,
        },

        // ── MEN'S WEAR ─────────────────────────────────
        {
            id: 'MN4001',
            name: 'Royal Blue Silk Sherwani with Heavy Zardozi Embroidery',
            sku: 'MN4001',
            category: 'Men',
            subcategory: 'Sherwani',
            price: 45000,
            compareAtPrice: 55000,
            currency: '₹',
            deliveryDays: '35 to 40 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1584,
            images: [
                './images/image-6.webp',
                './images/image-7.webp',
                './images/image-5.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'XXL (44)', value: 'XXL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Sherwani Measurements',
            details: {
                fabric: 'Pure Silk',
                work: 'Zardozi, Dabka, Pearl Embroidery',
                blouse: 'N/A',
                dupatta: 'Stole Included',
                lining: 'Cotton Lining',
                weight: '3.0 kg (approx)',
                occasion: 'Wedding, Groom Wear, Reception',
                washCare: 'Dry Clean Only',
                deliveryTime: '35–40 Working Days',
            },
            description: `<p>Look every inch the king in this <strong>Royal Blue Silk Sherwani</strong> with exquisite zardozi embroidery. Handcrafted for the modern groom.</p>
<ul><li>Pure silk with heavy zardozi work</li><li>Churidar and stole included</li><li>Made to your exact measurements</li></ul>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 35–40 Working Days</li><li>International: 40–50 Working Days</li></ul>`,
        },
        {
            id: 'MN4002',
            name: 'Ivory Silk Kurta Pyjama with Gold Thread Work',
            sku: 'MN4002',
            category: 'Men',
            subcategory: 'Kurta Pyjama',
            price: 12500,
            compareAtPrice: 15000,
            currency: '₹',
            deliveryDays: '7 to 10 Working Days',
            availability: 'In Stock',
            emiPerMonth: 440,
            images: [
                './images/image-4.webp',
                './images/image-5.webp',
                './images/image-6.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'XXL (44)', value: 'XXL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Kurta Measurements',
            details: {
                fabric: 'Pure Silk',
                work: 'Gold Thread Embroidery',
                blouse: 'N/A',
                dupatta: 'N/A',
                lining: 'Cotton Inner',
                weight: '1.2 kg (approx)',
                occasion: 'Festive, Puja, Wedding Guest',
                washCare: 'Dry Clean Recommended',
                deliveryTime: '7–10 Working Days',
            },
            description: `<p>An elegant <strong>Ivory Silk Kurta Pyjama</strong> with subtle gold thread embroidery. Perfect for festive occasions and wedding celebrations.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 7–10 Working Days</li><li>International: 12–18 Working Days</li></ul>`,
        },
        {
            id: 'MN4003',
            name: 'Maroon Velvet Indo-Western Sherwani with Brooch',
            sku: 'MN4003',
            category: 'Men',
            subcategory: 'Indo-Western',
            price: 38000,
            compareAtPrice: 46000,
            currency: '₹',
            deliveryDays: '35 to 40 Working Days',
            availability: 'In Stock',
            emiPerMonth: 1338,
            images: [
                './images/image-7.webp',
                './images/image-6.webp',
                './images/image-4.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Sherwani Measurements',
            details: {
                fabric: 'Velvet',
                work: 'Embroidery, Brooch Detail',
                blouse: 'N/A',
                dupatta: 'Stole Included',
                lining: 'Satin Lining',
                weight: '2.8 kg (approx)',
                occasion: 'Wedding, Reception, Engagement',
                washCare: 'Dry Clean Only',
                deliveryTime: '35–40 Working Days',
            },
            description: `<p>A fusion of tradition and modernity — this <strong>Maroon Velvet Indo-Western Sherwani</strong> with an elegant brooch detail is designed for the contemporary groom.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 35–40 Working Days</li><li>International: 40–50 Working Days</li></ul>`,
        },
        {
            id: 'MN4004',
            name: 'Black Bandhgala Nehru Jacket with Pocket Square',
            sku: 'MN4004',
            category: 'Men',
            subcategory: 'Nehru Jacket',
            price: 8500,
            compareAtPrice: 10500,
            currency: '₹',
            deliveryDays: '5 to 7 Working Days',
            availability: 'In Stock',
            emiPerMonth: 299,
            images: [
                './images/image-5.webp',
                './images/image-6.webp',
                './images/image-7.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'XXL (44)', value: 'XXL' },
            ],
            measurementLink: 'Jacket Measurements',
            details: {
                fabric: 'Premium Polyester Blend',
                work: 'Minimal, Pocket Square Included',
                blouse: 'N/A',
                dupatta: 'N/A',
                lining: 'Inner Lining',
                weight: '0.8 kg (approx)',
                occasion: 'Casual, Semi-Formal, Festive',
                washCare: 'Dry Clean Recommended',
                deliveryTime: '5–7 Working Days',
            },
            description: `<p>Elevate any outfit with this sharp <strong>Black Bandhgala Nehru Jacket</strong>. Comes with a matching pocket square for a polished look.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 5–7 Working Days</li><li>International: 10–15 Working Days</li></ul>`,
        },

        // ── MORE WOMEN'S PRODUCTS ──────────────────────
        {
            id: 'GW5001',
            name: 'Burgundy Velvet Floor-Length Designer Gown with Cape Sleeves',
            sku: 'GW5001',
            category: 'Women',
            subcategory: 'Gowns',
            price: 27500,
            compareAtPrice: 33000,
            currency: '₹',
            deliveryDays: '30 to 35 Working Days',
            availability: 'In Stock',
            emiPerMonth: 968,
            images: [
                './images/image-3.webp',
                './images/image-2.webp',
                './images/image-1.webp',
            ],
            sizes: [
                { label: '--Select--', value: '' },
                { label: 'XS (34)', value: 'XS' },
                { label: 'S (36)', value: 'S' },
                { label: 'M (38)', value: 'M' },
                { label: 'L (40)', value: 'L' },
                { label: 'XL (42)', value: 'XL' },
                { label: 'Custom Size', value: 'CUSTOM' },
            ],
            measurementLink: 'Gown Measurements',
            details: {
                fabric: 'Velvet with Net Cape',
                work: 'Stone Embellishment',
                blouse: 'N/A (Full Gown)',
                dupatta: 'N/A',
                lining: 'Satin Inner',
                weight: '2.5 kg (approx)',
                occasion: 'Reception, Award Night, Cocktail',
                washCare: 'Dry Clean Only',
                deliveryTime: '30–35 Working Days',
            },
            description: `<p>Steal the spotlight in this stunning <strong>Burgundy Velvet Floor-Length Gown</strong> with dramatic cape sleeves. A bold choice for special occasions.</p>`,
            shippingInfo: `<p><strong>Free Worldwide Shipping</strong></p><ul><li>Domestic: 30–35 Working Days</li><li>International: 35–45 Working Days</li></ul>`,
        },

    ];

    // ── Expose globally ─────────────────────────────────
    if (typeof window !== 'undefined') {
        window.ProductsCatalog = ProductsCatalog;
    }
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = ProductsCatalog;
    }

})();
